package com.groupe9.model;
// Generated 9 mars 2022, 10:44:53 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boissons generated by hbm2java
 */
@Entity
@Table(name = "boissons", catalog = "restaurant")
public class Boissons implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String type;
	private byte[] image;
	private Set<Periodes> periodeses = new HashSet<Periodes>(0);
	private Set<ComandeBoissons> comandeBoissonses = new HashSet<ComandeBoissons>(0);

	public Boissons() {
	}

	public Boissons(String nom, String type, byte[] image) {
		this.nom = nom;
		this.type = type;
		this.image = image;
	}

	public Boissons(String nom, String type, byte[] image, Set<Periodes> periodeses,
			Set<ComandeBoissons> comandeBoissonses) {
		this.nom = nom;
		this.type = type;
		this.image = image;
		this.periodeses = periodeses;
		this.comandeBoissonses = comandeBoissonses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boissons")
	public Set<Periodes> getPeriodeses() {
		return this.periodeses;
	}

	public void setPeriodeses(Set<Periodes> periodeses) {
		this.periodeses = periodeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boissons")
	public Set<ComandeBoissons> getComandeBoissonses() {
		return this.comandeBoissonses;
	}

	public void setComandeBoissonses(Set<ComandeBoissons> comandeBoissonses) {
		this.comandeBoissonses = comandeBoissonses;
	}

}
