package com.groupe9.model;
// Generated 9 mars 2022, 10:44:53 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComandeBoissons generated by hbm2java
 */
@Entity
@Table(name = "comande_boissons", catalog = "restaurant")
public class ComandeBoissons implements java.io.Serializable {

	private Integer id;
	private Boissons boissons;
	private Commandes commandes;

	public ComandeBoissons() {
	}

	public ComandeBoissons(Boissons boissons, Commandes commandes) {
		this.boissons = boissons;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "boisson_id", nullable = false)
	public Boissons getBoissons() {
		return this.boissons;
	}

	public void setBoissons(Boissons boissons) {
		this.boissons = boissons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commande_id", nullable = false)
	public Commandes getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Commandes commandes) {
		this.commandes = commandes;
	}

}
