package com.groupe9.model;
// Generated 9 mars 2022, 10:44:53 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menus generated by hbm2java
 */
@Entity
@Table(name = "menus", catalog = "restaurant")
public class Menus implements java.io.Serializable {

	private Integer id;
	private String nom;
	private Date createdAt;
	private Set<Periodes> periodeses = new HashSet<Periodes>(0);

	public Menus() {
	}

	public Menus(String nom, Date createdAt) {
		this.nom = nom;
		this.createdAt = createdAt;
	}

	public Menus(String nom, Date createdAt, Set<Periodes> periodeses) {
		this.nom = nom;
		this.createdAt = createdAt;
		this.periodeses = periodeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menus")
	public Set<Periodes> getPeriodeses() {
		return this.periodeses;
	}

	public void setPeriodeses(Set<Periodes> periodeses) {
		this.periodeses = periodeses;
	}

}
