package com.groupe9.model;
// Generated 9 mars 2022, 10:44:53 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodes generated by hbm2java
 */
@Entity
@Table(name = "periodes", catalog = "restaurant")
public class Periodes implements java.io.Serializable {

	private Integer id;
	private Boissons boissons;
	private Menus menus;
	private Plats plats;
	private Date periode;

	public Periodes() {
	}

	public Periodes(Date periode) {
		this.periode = periode;
	}

	public Periodes(Boissons boissons, Menus menus, Plats plats, Date periode) {
		this.boissons = boissons;
		this.menus = menus;
		this.plats = plats;
		this.periode = periode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "boisson_id")
	public Boissons getBoissons() {
		return this.boissons;
	}

	public void setBoissons(Boissons boissons) {
		this.boissons = boissons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id")
	public Menus getMenus() {
		return this.menus;
	}

	public void setMenus(Menus menus) {
		this.menus = menus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plat_id")
	public Plats getPlats() {
		return this.plats;
	}

	public void setPlats(Plats plats) {
		this.plats = plats;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "periode", nullable = false, length = 19)
	public Date getPeriode() {
		return this.periode;
	}

	public void setPeriode(Date periode) {
		this.periode = periode;
	}

}
